# Generated by Django 4.0.6 on 2022-07-18 08:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutus_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='greeting',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
