# Generated by Django 4.0.6 on 2022-08-23 08:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchArena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('thumnail', models.ImageField(blank=True, default='images/default.jfif', upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jfif', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='position',
            field=models.CharField(choices=[('Professor', '1'), ('PhD', '2'), ('MS', '3'), ('Undergraduate', '4')], max_length=13),
        ),
    ]
