# Generated by Django 4.0.6 on 2022-08-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_researcharena_alter_aboutus_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcharena',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
