# Generated by Django 4.0.6 on 2022-08-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_publictions_alter_publications_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('client', models.CharField(max_length=100)),
                ('statue', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Scheduled', 'Scheduled'), ('Pending', 'Pending')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('users', models.ManyToManyField(related_name='users', to='core.aboutus')),
            ],
        ),
    ]
