# Generated by Django 4.0.6 on 2022-09-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pictureca'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=None, upload_to='images/indexresearch')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='publications',
            name='category',
            field=models.CharField(choices=[('International Papers', 'International Papers'), ('International Conference', 'International Conference'), ('Domestic Papers', 'Domestic Papers'), ('Domestic Conference', 'Domestic Conference'), ('Patents', 'Patents')], max_length=30),
        ),
    ]
