# Generated by Django 4.0.6 on 2022-07-21 16:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_professor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['date']},
        ),
    ]
