# Generated by Django 4.0.6 on 2022-07-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_publictions_alter_timeline_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='position',
            field=models.CharField(choices=[('Professor', 'AProf'), ('PhD', 'BPhD'), ('MS', 'CMS'), ('Undergraduate', 'DUn'), ('Alumni', 'EAL')], max_length=13),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('News', 'Ne'), ('Research', 'Re')], max_length=8),
        ),
    ]
