# Generated by Django 4.0.6 on 2022-08-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_aboutus_category_aboutus_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='title',
            field=models.CharField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
