# Generated by Django 4.0.6 on 2022-08-27 07:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_researcharena_dt_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Journal', 'Journal'), ('Conference', 'Conference'), ('Patents', 'Patents')], max_length=12)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('link', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, default=None, upload_to='files/')),
                ('members', models.ManyToManyField(related_name='member', to='core.aboutus')),
            ],
        ),
    ]
