# Generated by Django 4.0.6 on 2022-09-21 11:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_indexresearch_alter_publications_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoVedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, default='images/img.jpg', upload_to='post_images')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('descirption', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('News', 'Ne'), ('Research', 'Re'), ('Outstanding', 'Os')], max_length=20),
        ),
    ]
