# Generated by Django 4.0.6 on 2022-07-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutus_professor_purpose_post_descirption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='category',
            field=models.CharField(choices=[('AL', 'Alumni'), ('LA', 'LabMember')], default='LA', max_length=2),
        ),
    ]
