# Generated by Django 4.0.6 on 2022-08-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_purpose_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default='2020-1-1'),
            preserve_default=False,
        ),
    ]
