# Generated by Django 4.0.6 on 2022-08-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_publications_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publictions',
        ),
        migrations.AlterField(
            model_name='publications',
            name='date',
            field=models.DateField(),
        ),
    ]
