# Generated by Django 4.0.6 on 2022-09-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureCa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=None, upload_to='images/indexPic')),
            ],
        ),
    ]
