# Generated by Django 4.0.6 on 2022-09-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_professor_greeting_professor_member_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proftimeline',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
